### ISSUE TITLE
Does not compile on Xcode 5 and later

### ISSUE THREAD

**Issue by probonopd** [seanwhitsell/Pressure#1]
Trying to compile on Xcode Version 5.1.1 on OS X 10.9 I get `error: garbage collection is no longer supported`. According to [this](http://stackoverflow.com/questions/22335957/core-plot-and-xcode-5-1-how-to-convert-core-plot-to-arc) page,

> Xcode 5.1 doesn't require projects to use ARC, it just finally drops support for garbage collection. Core Plot was never a strictly garbage-collected framework, but it did support building for garbage collection. 
> 
> You can click on the "Not Now" option when presented with that dialog on opening the Core Plot project, then go to the project build settings. Blank out or remove the GCC_ENABLE_OBJC_GC setting under the user settings at the bottom of the project and the project will build just fine as a manually reference counted target. That's perfectly usable within an ARC or non-ARC application.

However, even with that I get more compile errors which would need to be cleaned up.

**Comment by benshan** [comment]
@probonopd I made some quick changes to get this running again with xcode7.2. You might want to check out the remaining warnings and see if additional changes are needed to restore functionality.

**Comment by probonopd** [comment]
Thanks @benshan - how am I supposed to fix `Missing dependency target "CorePlot Mac (from CorePlot.xcodeproj)"`?

**Comment by benshan** [comment]
Pull latest and use:
     git submodule update --init --recursive

**Comment by probonopd** [comment]
Thanks. Getting lots of errors. I guess I will have to update OS X and Xcode in order to keep up with CorePlot.

**Comment by seanwhitsell** [comment]
git clone https://github.com/seanwhitsell/Pressure.git
cd Pressure/
git submodule update --init --recursive
cd Pressure
open Pressure.xcodeproj

Change the target to "Pressure" and Run.

I got 94 warnings that I'll look at, but the App runs fine. XCode 7.2 on El Capitan.
